apiVersion: app.k8s.io/v1beta1
kind: Application
metadata:
  name: bookinfo
spec:
  componentKinds:
  - group: core.hybridapp.io
    kind: Deployable
  selector:
    matchLabels:
      ham-sample-app: bookinfo    
---
apiVersion: core.hybridapp.io/v1alpha1
kind: PlacementRule
metadata:
  name: ham-sample-bookinfo
spec:
  targets:
  - apiVersion: cluster.open-cluster-management.io/v1
    kind: ManagedCluster
    name: toronto
---
apiVersion: core.hybridapp.io/v1alpha1
kind: Deployable
metadata:
  labels:
    tools.hybridapp.io/application-3f74c232-afb6-4477-8d9f-e455572b66d2: 3f74c232-afb6-4477-8d9f-e455572b66d2
  name: service-bookinfo-details
spec:
  hybridtemplates:
  - deployerType: kubernetes
    template:
      apiVersion: v1
      kind: Service
      metadata:
        name: details
        labels:
          ham-sample-app: bookinfo
          app: details
          service: details
      spec:
        ports:
        - port: 9080
          name: http
        selector:
          app: details
  placement:
    placementRef:
      name: ham-sample-bookinfo
---
apiVersion: core.hybridapp.io/v1alpha1
kind: Deployable
metadata:
  labels:
    ham-sample-app: bookinfo
  name: serviceaccount-bookinfo-details
spec:
  hybridtemplates:
  - deployerType: kubernetes
    template:
      apiVersion: v1
      kind: ServiceAccount
      metadata:
        name: bookinfo-details
        labels:
          ham-sample-app: bookinfo
          account: details
  placement:
    placementRef:
      name: ham-sample-bookinfo
---
apiVersion: core.hybridapp.io/v1alpha1
kind: Deployable
metadata:
  labels:
    ham-sample-app: bookinfo
  name: deployment-bookinfo-details-v1
spec:
  hybridtemplates:
  - deployerType: kubernetes
    template:
      apiVersion: apps/v1
      kind: Deployment
      metadata:
        name: details-v1
        labels:
          ham-sample-app: bookinfo
          app: details
          version: v1
      spec:
        replicas: 1
        selector:
          matchLabels:
            app: details
            version: v1
        template:
          metadata:
            labels:
              app: details
              version: v1
          spec:
            serviceAccountName: bookinfo-details
            containers:
            - name: details
              image: docker.io/istio/examples-bookinfo-details-v1:1.16.0
              imagePullPolicy: IfNotPresent
              ports:
              - containerPort: 9080
  placement:
    placementRef:
      name: ham-sample-bookinfo
---
apiVersion: core.hybridapp.io/v1alpha1
kind: Deployable
metadata:
  labels:
    ham-sample-app: bookinfo
  name: service-bookinfo-productpage
spec:
  hybridtemplates:
  - deployerType: kubernetes
    template:
      apiVersion: v1
      kind: Service
      metadata:
        name: productpage
        labels:
          ham-sample-app: bookinfo
          app: productpage
          service: productpage
      spec:
        ports:
        - port: 9080
          name: http
        selector:
          app: productpage
  placement:
    placementRef:
      name: ham-sample-bookinfo
---
apiVersion: core.hybridapp.io/v1alpha1
kind: Deployable
metadata:
  labels:
    ham-sample-app: bookinfo
  name: serviceaccount-bookinfo-bookinfo-productpage
spec:
  hybridtemplates:
  - deployerType: kubernetes
    template:
      apiVersion: v1
      kind: ServiceAccount
      metadata:
        name: bookinfo-productpage
        labels:
          ham-sample-app: bookinfo
          account: productpage
  placement:
    placementRef:
      name: ham-sample-bookinfo
---
apiVersion: core.hybridapp.io/v1alpha1
kind: Deployable
metadata:
  labels:
    ham-sample-app: bookinfo
  name: deployment-bookinfo-productpage-v1
spec:
  hybridtemplates:
  - deployerType: kubernetes
    template:
      apiVersion: apps/v1
      kind: Deployment
      metadata:
        name: productpage-v1
        labels:
          ham-sample-app: bookinfo
          app: productpage
          version: v1
      spec:
        replicas: 1
        selector:
          matchLabels:
            app: productpage
            version: v1
        template:
          metadata:
            labels:
              app: productpage
              version: v1
          spec:
            serviceAccountName: bookinfo-productpage
            containers:
            - name: productpage
              image: docker.io/istio/examples-bookinfo-productpage-v1:1.16.0
              imagePullPolicy: IfNotPresent
              ports:
              - containerPort: 9080
              volumeMounts:
              - name: tmp
                mountPath: /tmp
            volumes:
            - name: tmp
              emptyDir: {}
  placement:
    placementRef:
      name: ham-sample-bookinfo
---
apiVersion: core.hybridapp.io/v1alpha1
kind: Deployable
metadata:
  labels:
    ham-sample-app: bookinfo
  name: service-bookinfo-ratings
spec:
  hybridtemplates:
  - deployerType: kubernetes
    template:
      apiVersion: v1
      kind: Service
      metadata:
        name: ratings
        labels:
          ham-sample-app: bookinfo
          app: ratings
          service: ratings
      spec:
        ports:
        - port: 9080
          name: http
        selector:
          app: ratings
  placement:
    placementRef:
      name: ham-sample-bookinfo
---
apiVersion: core.hybridapp.io/v1alpha1
kind: Deployable
metadata:
  labels:
    ham-sample-app: bookinfo
  name: serviceaccount-bookinfo-bookinfo-ratings
spec:
  hybridtemplates:
  - deployerType: kubernetes
    template:
      apiVersion: v1
      kind: ServiceAccount
      metadata:
        name: bookinfo-ratings
        labels:
          ham-sample-app: bookinfo
          account: ratings
  placement:
    placementRef:
      name: ham-sample-bookinfo
---
apiVersion: core.hybridapp.io/v1alpha1
kind: Deployable
metadata:
  labels:
    ham-sample-app: bookinfo
  name: deployment-bookinfo-ratings-v1
spec:
  hybridtemplates:
  - deployerType: kubernetes
    template:
      apiVersion: apps/v1
      kind: Deployment
      metadata:
        name: ratings-v1
        labels:
          ham-sample-app: bookinfo
          app: ratings
          version: v1
      spec:
        replicas: 1
        selector:
          matchLabels:
            app: ratings
            version: v1
        template:
          metadata:
            labels:
              app: ratings
              version: v1
          spec:
            serviceAccountName: bookinfo-ratings
            containers:
            - name: ratings
              image: docker.io/istio/examples-bookinfo-ratings-v1:1.16.0
              imagePullPolicy: IfNotPresent
              ports:
              - containerPort: 9080
  placement:
    placementRef:
      name: ham-sample-bookinfo
---
apiVersion: core.hybridapp.io/v1alpha1
kind: Deployable
metadata:
  labels:
    ham-sample-app: bookinfo
  name: service-bookinfo-reviews
spec:
  hybridtemplates:
  - deployerType: kubernetes
    template:
      apiVersion: v1
      kind: Service
      metadata:
        name: reviews
        labels:
          ham-sample-app: bookinfo
          app: reviews
          service: reviews
      spec:
        ports:
        - port: 9080
          name: http
        selector:
          app: reviews
  placement:
    placementRef:
      name: ham-sample-bookinfo
---
apiVersion: core.hybridapp.io/v1alpha1
kind: Deployable
metadata:
  labels:
    ham-sample-app: bookinfo
  name: serviceaccount-bookinfo-bookinfo-reviews
spec:
  hybridtemplates:
  - deployerType: kubernetes
    template:
      apiVersion: v1
      kind: ServiceAccount
      metadata:
        name: bookinfo-reviews
        labels:
          ham-sample-app: bookinfo
          account: reviews
  placement:
    placementRef:
      name: ham-sample-bookinfo
---
apiVersion: core.hybridapp.io/v1alpha1
kind: Deployable
metadata:
  labels:
    ham-sample-app: bookinfo
  name: deployment-bookinfo-reviews-v1
spec:
  hybridtemplates:
  - deployerType: kubernetes
    template:
      apiVersion: apps/v1
      kind: Deployment
      metadata:
        name: reviews-v1
        labels:
          ham-sample-app: bookinfo
          app: reviews
          version: v1
      spec:
        replicas: 1
        selector:
          matchLabels:
            app: reviews
            version: v1
        template:
          metadata:
            labels:
              app: reviews
              version: v1
          spec:
            serviceAccountName: bookinfo-reviews
            containers:
            - name: reviews
              image: docker.io/istio/examples-bookinfo-reviews-v1:1.16.0
              imagePullPolicy: IfNotPresent
              env:
              - name: LOG_DIR
                value: "/tmp/logs"
              ports:
              - containerPort: 9080
              volumeMounts:
              - name: tmp
                mountPath: /tmp
              - name: wlp-output
                mountPath: /opt/ibm/wlp/output
            volumes:
            - name: wlp-output
              emptyDir: {}
            - name: tmp
              emptyDir: {}
  placement:
    placementRef:
      name: ham-sample-bookinfo
---
apiVersion: core.hybridapp.io/v1alpha1
kind: Deployable
metadata:
  labels:
    ham-sample-app: bookinfo
  name: deployment-bookinfo-reviews-v2
spec:
  hybridtemplates:
  - deployerType: kubernetes
    template:
      apiVersion: apps/v1
      kind: Deployment
      metadata:
        name: reviews-v2
        labels:
          ham-sample-app: bookinfo
          app: reviews
          version: v2
      spec:
        replicas: 1
        selector:
          matchLabels:
            app: reviews
            version: v2
        template:
          metadata:
            labels:
              app: reviews
              version: v2
          spec:
            serviceAccountName: bookinfo-reviews
            containers:
            - name: reviews
              image: docker.io/istio/examples-bookinfo-reviews-v2:1.16.0
              imagePullPolicy: IfNotPresent
              env:
              - name: LOG_DIR
                value: "/tmp/logs"
              ports:
              - containerPort: 9080
              volumeMounts:
              - name: tmp
                mountPath: /tmp
              - name: wlp-output
                mountPath: /opt/ibm/wlp/output
            volumes:
            - name: wlp-output
              emptyDir: {}
            - name: tmp
              emptyDir: {}
  placement:
    placementRef:
      name: ham-sample-bookinfo
---
apiVersion: core.hybridapp.io/v1alpha1
kind: Deployable
metadata:
  labels:
    ham-sample-app: bookinfo
  name: deployment-bookinfo-reviews-v3
spec:
  hybridtemplates:
  - deployerType: kubernetes
    template:
      apiVersion: apps/v1
      kind: Deployment
      metadata:
        name: reviews-v3
        labels:
          ham-sample-app: bookinfo
          app: reviews
          version: v3
      spec:
        replicas: 1
        selector:
          matchLabels:
            app: reviews
            version: v3
        template:
          metadata:
            labels:
              app: reviews
              version: v3
          spec:
            serviceAccountName: bookinfo-reviews
            containers:
            - name: reviews
              image: docker.io/istio/examples-bookinfo-reviews-v3:1.16.0
              imagePullPolicy: IfNotPresent
              env:
              - name: LOG_DIR
                value: "/tmp/logs"
              ports:
              - containerPort: 9080
              volumeMounts:
              - name: tmp
                mountPath: /tmp
              - name: wlp-output
                mountPath: /opt/ibm/wlp/output
            volumes:
            - name: wlp-output
              emptyDir: {}
            - name: tmp
              emptyDir: {}
  placement:
    placementRef:
      name: ham-sample-bookinfo
