apiVersion: core.hybridapp.io/v1alpha1
kind: PlacementRule
metadata:
  name: ham-sample-bookinfo
spec:
  targets:
  - apiVersion: cluster.open-cluster-management.io/v1
    kind: ManagedCluster
    name: toronto