apiVersion: app.k8s.io/v1beta1
kind: Application
metadata:
  name: bookinfo
  annotations:
    core.hybridapp.io/hybrid-discovery: "enabled"
    core.hybridapp.io/hybrid-discovery-clusterscoped: "true"
    #tools.hybridapp.io/hybrid-discovery-target: "{\"namespace\":\"toronto\",\"name\":\"toronto\"}"
    #tools.hybridapp.io/hybrid-discovery-create-assembler: "true"
spec:
  selector:
    matchLabels:
      ham-sample-app: bookinfo
  componentKinds:
    - group: v1
      kind: Service
    - group: apps
      kind: Deployment
    - group: v1
      kind: ServiceAccount