apiVersion: app.k8s.io/v1beta1
kind: Application
metadata:
  name: ham-sample-gbapp
spec:
  componentKinds:
  - group: core.hybridapp.io
    kind: Deployable
  selector:
    matchLabels:
      ham-sample-app: guestbook
