apiVersion: core.hybridapp.io/v1alpha1
kind: Deployable
metadata:
  labels:
    ham-sample-app: guestbook
  name: deployment-guestbook-frontend
spec:
  hybridtemplates:
  - deployerType: kubernetes
    template:
      apiVersion: apps/v1
      kind: Deployment
      metadata:
        annotations:
        name: frontend
      spec:
        replicas: 3
        selector:
          matchLabels:
            app: guestbook
            tier: frontend
        strategy:
          rollingUpdate:
            maxSurge: 25%
            maxUnavailable: 25%
          type: RollingUpdate
        template:
          metadata:
            creationTimestamp: null
            labels:
              app: guestbook
              tier: frontend
          spec:
            containers:
            - env:
              - name: GET_HOSTS_FROM
                value: dns
              image: gcr.io/google-samples/gb-frontend:v4
              imagePullPolicy: IfNotPresent
              name: php-redis
              ports:
              - containerPort: 80
                protocol: TCP
              resources:
                requests:
                  cpu: 100m
                  memory: 100Mi
              terminationMessagePath: /dev/termination-log
              terminationMessagePolicy: File
  placement:
    placementRef:
      name: ham-sample-guestbook
---
apiVersion: core.hybridapp.io/v1alpha1
kind: Deployable
metadata:
  labels:
    ham-sample-app: guestbook
  name: service-guestbook-frontend
spec:
  hybridtemplates:
  - deployerType: kubernetes
    template:
      apiVersion: v1
      kind: Service
      metadata:
        labels:
          app: guestbook
          ham-sample-app: guestbook
          tier: frontend
        name: frontend
      spec:
        ports:
        - port: 80
        selector:
          app: guestbook
          tier: frontend
        type: NodePort
  placement:
    placementRef:
      name: ham-sample-guestbook
